language: node_js
node_js:
  - "stable"
cache:
  yarn: true
  directories:
    - node_modules
before_deploy:
 - yarn build
deploy:
  provider: heroku
  api_key:
    secure: $heroku_api
  app: markdown-previewer-srl
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master

